export const ROLES = {
  LEARNER: 'LEARNER',
  PEER_MENTOR: 'PEER_MENTOR',
  FACULTY_MENTOR: 'FACULTY_MENTOR',
  ADMIN: 'ADMIN',
}

export const REGISTERABLE_ROLES = [
  ROLES.LEARNER,
  ROLES.PEER_MENTOR,
  ROLES.FACULTY_MENTOR,
]

export const ALL_ROLES = Object.values(ROLES)
